name: frontend
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.3
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/font/
    - assets/icon/
    - assets/image/

  fonts:
    - family: EXO-B
      fonts:
        - asset: assets/font/Exo2-Black.ttf
    - family: EXO-R
      fonts:
        - asset: assets/font/Exo2-Regular.ttf
    - family: Roboto-B
      fonts:
        - asset: assets/font/Roboto-Black.ttf
    - family: Roboto-R
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
